services:
  # O Cérebro do Jogo
  orchestrator:
    build:
      context: ./orchestrator
    container_name: game-orchestrator
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./levels:/app/levels
      - ./scratch:/app/scratch
    restart: always

  # A Interface Gráfica
  web:
    build:
      context: .
    container_name: game-web
    network_mode: "host"
    restart: always
